### ISSUE TITLE
Issue Reproducing Results on RAF Dataset, Incomplete config

### ISSUE THREAD

**Issue by pantheon5100** [penn-waves-lab/AVR#1]
Dear Author,

Thank you for your great work. I encountered an issue when running the training on the RAF dataset. After setting up the environment and dataset, I ran:

`python avr_runner.py --config ./config_files/avr_raf.yml --dataset_dir /data/RAF/FurnishedRoomSplit`

but received the following error:
![image](https://github.com/user-attachments/assets/e8355459-af56-4069-b61c-a0a117abf86a)

It seems there might be a missing configuration in avr_raf.yml. Could you please help resolve this?

Thank you!

**Comment by ZitongLan** [comment]
Thanks for you interests! I am traveling back from NeurIPS and will come back and fix the issue in the following days. Stay tuned!

**Comment by ZitongLan** [comment]
Hi @pantheon5100 
I’ve addressed this issue in commit [Fix RAF Error](https://github.com/penn-waves-lab/AVR/commit/e5669169916b161b54c9449c5b3f51f52b2a7c2e). The bug is due to an inconsistence variable name in the configurations.
